spring.application.name: serverOat
spring:
  mvc:
    view:
      prefix: templates/
      suffix: .html
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
server:
  port: 8080
jwt:
  secret: b332b4c3631edee13cfb25a504da3d06087079121f46fe645c66372664cbabc3
  lifetime: 200000m
